### ISSUE TITLE
项目期望

### ISSUE THREAD

**Issue by xem1987** [geekidea/spring-boot-plus#1]
现在看来，项目只是刚刚起步，作为一个应用服务生产的开发基础，还有差很多，不知道作者项目计划是怎么样的？具体会有哪些功能和模块？最终解决哪些开发中的痛点？

**Comment by springboot-plus** [comment]
- 你好，非常感谢你的关注，目前spring-boot-plus项目目前以可以使用来作为快速开发的基础脚手架。
- 后期还会进行功能模块增强，加入更多开发中常用到的技术模块和公共配置，也会不断晚上使用文档。
- spring-boot-plus V2.0规划，会进行模块拆分，方便更好的集成和使用！
- spring-boot-plus 的主要理念和重心是针对小型项目快速开发集成使用的。
- 后期会有spring-cloud-plus 微服务快速开发脚手架项目，敬请期待！
- 同时，也非常欢迎大家能加入到开源项目中，成为一个commiter，一起完善维护好开源项目！

**Comment by wenyuantc** [comment]
希望 spring-cloud-plus 使用nacos来做注册中心

**Comment by wenyuantc** [comment]
其实在看到你这个项目之前，我还看到了apiboot  官网是http://apiboot.minbox.io/zh-cn/  作者你也可以基于这个开发

**Comment by springboot-plus** [comment]
> 希望 spring-cloud-plus 使用nacos来做注册中心

嗯，谢谢你的反馈，目前准备发布的1.0版本的服务注册中心是Eureka
后面V2.0会考虑集成阿里巴巴的相关开源组件，敬请期待！

**Comment by springboot-plus** [comment]
> 其实在看到你这个项目之前，我还看到了apiboot 官网是http://apiboot.minbox.io/zh-cn/ 作者你也可以基于这个开发

嗯，谢谢你的建议，后面会参考各个优秀的开源项目，并结合实际项目情况，进行组件集成和功能增强！
