### ISSUE TITLE
加群官网地址的答案是啥？ 输了都进不去

### ISSUE THREAD

**Issue by Chester-Lin** [geekidea/spring-boot-plus#118]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by springboot-plus** [comment]
springboot.plus

**Comment by sungatetop** [comment]
还是进不去？？

**Comment by springboot-plus** [comment]
> 还是进不去？？

Are You Sure ??? !!!
