### ISSUE TITLE
spring boot admin如何加入用户名和密码保证安全性

### ISSUE THREAD

**Issue by tianshishouhu** [geekidea/spring-boot-plus#14]

**Comment by springboot-plus** [comment]
- [](http://codecentric.github.io/spring-boot-admin/2.1.6/#securing-spring-boot-admin)
- 后面集成Spring Security的时候，会完善

**Comment by springboot-plus** [comment]
V2.0 admin模块已集成Spring Security，Spring Boot Admin 登录时会提示输入账号密码
