### ISSUE TITLE
SpringBoot Admin 集成显示日志问题

### ISSUE THREAD

**Issue by jianxia612** [geekidea/spring-boot-plus#15]
首先感谢开源你的成果，我最近在测试SpringBoot Admin，在看到您的项目之中集成了此包。
但是我发现了一个问题，SpringBoot Admin 是可以在线查看日志的，这样的好处可以直接在线监控日志报错信息。但是我在开启SpringBoot Admin的日志信息后，会出现如下错误：说是输入显示输入流转换为json。
`org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class sun.nio.ch.ChannelInputStream]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class sun.nio.ch.ChannelInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0]->org.springframework.core.io.support.ResourceRegion["resource"]->org.springframework.core.io.FileSystemResource["inputStream"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:293) ~[spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:103) ~[spring-web-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) ~[spring-webmvc-5.1.8.RELEASE.jar:5.1.8.RELEASE]
`
最后我注销Jackson自定义转换器后即可，不过您已经在1.2里面解决此问题。不错我看看1.2是如何解决的。
![image](https://user-images.githubusercontent.com/10516256/62511829-0efb0a00-b848-11e9-9282-1ce594b4e7a9.png)

**Comment by springboot-plus** [comment]
- 你好，感谢你的关注和反馈
- 你反馈的Spring Boot Admin在线查看日志问题，V1.2.0-RELEASE版本已修复
- pull一下代码，再试一下

**Comment by wcc137** [comment]
出现这个错误是什么原因？我之前也碰到了

**Comment by springboot-plus** [comment]
JacksonConfig配置问题
本项目修复记录：
移除 JacksonConfig 类中的以下代码：
```java
List<MediaType> mediaTypes = new ArrayList<>();
        mediaTypes.add(MediaType.APPLICATION_JSON);
        mediaTypes.add(MediaType.APPLICATION_JSON_UTF8);
        mediaTypes.add(MediaType.TEXT_HTML);
        mediaTypes.add(new MediaType("application", "xml"));
        mediaTypes.add(new MediaType("text", "xml"));
        mediaTypes.add(new MediaType("application", "*+xml"));
        mediaTypes.add(MediaType.ALL);

        jackson2HttpMessageConverter.setSupportedMediaTypes(mediaTypes);
```

**Comment by jianxia612** [comment]
> 出现这个错误是什么原因？我之前也碰到了

主要就是Jackson的转换地方修改时候有问题，去掉楼主所说的哪一点即可 可以比较1.10与1.20的区别就知道。我也知道原因的；知识楼主已经发布1.20版本我就未细说啦。主要根源问题是楼主改写后缺少了通过输入InputStream日志文件流内容转换到json的类型缺失的原因；所以注释掉前面内容；使其为默认内容即可。
