### ISSUE TITLE
启用验证码后 登录报错

### ISSUE THREAD

**Issue by mixcg** [geekidea/spring-boot-plus#158]
从 redis 取缓存的验证码 jackson 序列化报错  

`org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Unrecognized token 'kVRf': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

**Comment by linmengmeng-1314** [comment]
```io.geekidea.springbootplus.config.RedisTemplateConfig```类中设置redis的value时，使用StringRedisSerializer序列化，不使用Json相关序列化
修改RedisTemplateConfig.redisTemplate方法中的
```java
redisTemplate.setValueSerializer(jsonRedisSerializer);
```
为
```java
redisTemplate.setValueSerializer(new StringRedisSerializer());
```
此时由于修改了redis存值的序列化方式，原本直接将对象存入redis的地方会报错，逐步修改redisTemplate.opsForValue().set()的使用，将值对象转成字符串后再存值（调用该对象的toString方法）。
