### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by dpnkrg** [geekidea/spring-boot-plus#169]
Hi @springboot-plus, @geekidea, 

Right Now, I am having this project and I am able to run this project from Intellij Idea. 
I just wanted to know, How to deploy this multimodule project to server like JBOSS, Tomcat, or Ktor (any of them) via the WAR file deployment.

Right now, the project works well from the IDE, but I am unable to create a workable WAR file from the existing project which will execute properly. 

**Need help in this**

**Comment by springboot-plus** [comment]
Hello, by the way, are you currently using spring boot plus or spring boot
