### ISSUE TITLE
WebMvcConfig.class：开启三个拦截器，excludePathPatterns没起作用

### ISSUE THREAD

**Issue by chencn** [geekidea/spring-boot-plus#20]
WebMvcConfig.class代码中被注释的jwtInterceptor，tokenTimeoutInterceptor，permissionInterceptor开启之后，excludePathPatterns没有生效，原因是路径有问题，应该转成list之后再传进去,修改如下:
![image](https://user-images.githubusercontent.com/5409429/63316976-9ade5d00-c343-11e9-8977-ea1da5237542.png)

**Comment by springboot-plus** [comment]
嗯，好的，谢谢，我改下属性配置映射

**Comment by springboot-plus** [comment]
```java
@Data
    public static class InterceptorConfig {

        /**
         * 排除路径
         */
        private String[] excludePath;

        /**
         * 包含的路径
         */
        private String[] includePath;

    }
```
##### 已修复此问题
