### ISSUE TITLE
权限那块是不是还没完善呀

### ISSUE THREAD

**Issue by lifeorwar** [geekidea/spring-boot-plus#3]
在用了，确实很省心的，给作者一个好评

**Comment by springboot-plus** [comment]
权限模块正在完善中

**Comment by DeelFeel** [comment]
> 权限模块正在完善中

角色权限模块是个重点，但是不要把整个框架重量级了，像那个renren，做了太多东西，反而不想用了。

**Comment by springboot-plus** [comment]
v1.4.0已完善用户角色权限管理
https://github.com/geekidea/spring-boot-plus/releases/tag/V1.4.0
