### ISSUE TITLE
druid monitor 控制台无法登录

### ISSUE THREAD

**Issue by sqskg** [geekidea/spring-boot-plus#74]
输入用户名/密码 无法登录被重定向当前页

**Comment by sqskg** [comment]
是不是druid控制台的认证和shrio的认证冲突了？

**Comment by springboot-plus** [comment]
shiro和druid配置冲突了，按照下面的方法配置，druid可以使用，会在下个版本修复
- 修改ShiroConfig.java，删除一下代码

```java
securityManager.setSessionManager(sessionManager());
```

```java
  /**
     * 禁用session
     *
     * @return
     */
    @Bean
    public DefaultSessionManager sessionManager() {
        DefaultSessionManager manager = new DefaultSessionManager();
        manager.setSessionValidationSchedulerEnabled(false);
        return manager;
    }
```

- 修改application.yml，druid设置为不拦截
```yml
/druid/**=anon
```

**Comment by sqskg** [comment]
very nice！亲测，调整有效！
昨天本人只修改了application.yaml的配置，设置为不拦截druid/** 没有调整代码，怎么也登录不上，通过今天的调整运行正常了。
![WX20191010-101305](https://user-images.githubusercontent.com/14267002/66533766-ad586400-eb46-11e9-89c7-679cca38c3db.png)
