### ISSUE TITLE
io.geekidea.springbootplus.common.param里没有get/set方法导致Controller里调用的报错

### ISSUE THREAD

**Issue by lifuchao** [geekidea/spring-boot-plus#86]
**Describe the bug**
如题

**Screenshots**
![image](https://user-images.githubusercontent.com/15504114/67381176-15369200-f5be-11e9-8152-33d7cc0ae39e.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chorme75
 - Version master

另外，顺便问一下能否多个表批量生成？现在貌似是只能单个表生成

**Comment by springboot-plus** [comment]
使用了Lombok，会自动生成get/set方法，请安装Lombok插件

**Comment by springboot-plus** [comment]
最新dev分支代码，已支持同时生成多个表
[https://github.com/geekidea/spring-boot-plus/blob/dev/src/test/java/io/geekidea/springbootplus/test/SpringBootPlusGenerator.java](https://github.com/geekidea/spring-boot-plus/blob/dev/src/test/java/io/geekidea/springbootplus/test/SpringBootPlusGenerator.java)

**Comment by lifuchao** [comment]
> 最新dev分支代码，已支持同时生成多个表
> https://github.com/geekidea/spring-boot-plus/blob/dev/src/test/java/io/geekidea/springbootplus/test/SpringBootPlusGenerator.java

多谢了啊。另外后续有没有考虑生成的时候给单元测试类一起生成了呢？
