### ISSUE TITLE
很多类里有log.XXX的地方都报错，log未定义

### ISSUE THREAD

**Issue by lifuchao** [geekidea/spring-boot-plus#87]
**Describe the bug**
如题

**Screenshots**
![image](https://user-images.githubusercontent.com/15504114/67385526-d86e9900-f5c5-11e9-88ba-f1af1236038c.png)

**Desktop (please complete the following information):**
 - OS:win10
 - Browser Chrome75
 - Version master

**Comment by springboot-plus** [comment]
https://springboot.plus/guide/idea-spring-boot-plus.html
