### ISSUE TITLE
事务不可用？！

### ISSUE THREAD

**Issue by huqiji** [geekidea/spring-boot-plus#88]
进行数据库操作的时候总是提示
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@9d1b881] will not be managed by Spring

事务处理提示
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5100d9b0] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1749b96e] will not be managed by Spring

有大神决绝一下吗？

**Comment by springboot-plus** [comment]
这是spring-boot-plus项目中出现的问题，还是？
